### ISSUE TITLE
Fix mp3 files with the right track number

### ISSUE THREAD

**Issue by raymanrt** [josharsh/100LinesOfCode#81]
mp3fix iterates through all files with the .mp3 extension within the current directory.

If the file name begins with a one-digit number that is not preceded by zero, rename the file to meet this standard.

**Comment by JannickTie** [comment]
Can't this issue be closed?  @raymanrt  @josharsh 
I like this tool a lot btw!

**Comment by raymanrt** [comment]
Thanx
